# Generated by Django 2.1 on 2019-01-14 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('note', models.TextField(max_length=240)),
                ('organization', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ContactBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('date_created', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.CharField(choices=[('WK', 'Work Phone Number'), ('PN', 'Cell Phone Number'), ('HM', 'Home Phone Number'), ('FX', 'Fax Number'), ('AD', 'Address'), ('PC', 'Zip/Postal Code'), ('WA', 'Website or Blog'), ('EV', 'Birthday, Anniversary, etc.'), ('MA', 'WhatsApp, Telegram, Messenger, etc.')], default='PN', max_length=2)),
                ('value', models.CharField(max_length=200)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactbook.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactbook.ContactBook'),
        ),
    ]
